server:
  port: 8080

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    org.springframework.cloud.consul: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] [%15.15t] %-40.40logger{39}: %m%n'

spring:
  cloud:
    consul:
      discovery:
        preferIpAddress: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  zipkin:
      # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
    baseUrl: http://192.168.99.100:9411/
  sleuth:
    sampler:
      percentage: 1.0

consumed.microservice.name: "microservice1"

turbine:
  aggregator:
    clusterConfig: microserviceconsumer
  appConfig: microserviceconsumer